name: Publish Iconsauce Core
on:
  workflow_dispatch:
jobs:
  build_test:
    name: Build and Test core
    uses: ./.github/workflows/test.yml
  publish:
    permissions:
      id-token: write
      contents: read
    needs: [build_test]
    name: Publish npm
    uses: iconsauce/.github/.github/workflows/publish-npm.yml@main
    secrets: inherit
