name: Publish Iconsauce Core
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  build_test:
    name: Build and Test core
    uses: ./.github/workflows/test.yml
  publish:
    needs: [build_test]
    name: Publish npm
    uses: iconsauce/.github/.github/workflows/publish-npm.yml@main
    secrets: inherit
