name: Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_call:
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: iconsauce/.github/.github/actions/setup-node@main
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test
